### ISSUE TITLE
Performs poorly on test case

### ISSUE THREAD

**Issue by vrossum** [stevenwatterson/GA#1]
The included test case should find x1=100, x2=200, but stops far from that.

Not sure if this is problem with the implementation or GAs in general.

**Comment by stevenwatterson** [comment]
Hi @vrossum 

Thanks for your interest in the package.  In the example code, the GA didn't reach the solution of (100,200) because an upper bound of (70,80) was imposed using the parameters (UB) to gaoptimset.  Hence, the GA coverged on (70,80).  I've now changed these upper bounds in the master branch so that they don't obstruct the GA from achieving the true solution in the test example.  Hope that that clears it up.

Steve.
